// English Questions
export const QUESTIONS_EN = {
    Kids: {
        truth: [
            "Have you ever gone to school without brushing?",
            "What's the biggest lie your mom found out?",
            "Who is your best friend and why?",
            "Which cartoon do you still secretly watch?",
            "Have you ever let someone copy your homework?",
            "Ever had a crush on a teacher?",
            "Have you fallen asleep in assembly?",
            "Have you ever danced in class and got caught?",
            "Which ice-cream could you eat every day?",
            "What's your funniest nickname?",
            "Ever snuck snacks and eaten them secretly?",
            "Are you ever scared of ghosts at night?",
            "If you had a superpower, what would it be?",
            "What weird food did you try and like?",
            "What's the most embarrassing thing at school?",
            "Which subject scares you the most?",
            "If you were principal for a day, what rule would you make?",
            "What's one thing you really don't like?",
            "Which pet would you pick if you could have any?",
            "Have you ever licked the cake before birthday cutting?"
        ],
        dare: [
            "Do your best cartoon character voice.",
            "Act like a Bollywood hero/heroin for 10 seconds.",
            "Dance like your noodles are shaking.",
            "Sing \"Old MacDonald\" with full drama.",
            "Pretend to be a robot and walk for 20 seconds.",
            "Do a tiny fashion show catwalk.",
            "Do the chicken dance.",
            "Try saying the alphabet backwards (as much as you can).",
            "Propose to a table with big emotions.",
            "Be a teacher and give everyone homework.",
            "Strike your favorite cartoon pose.",
            "Laugh like a joker for 10 seconds.",
            "Run in slow motion for 10 seconds.",
            "Use someone's shoe as a microphone and sing.",
            "Make an animal beatbox sound.",
            "Tap the table like a drum and pretend you're a tabla player.",
            "Style your hair in a silly way for one minute.",
            "Make 10 funny faces fast.",
            "Say a movie villain line dramatically.",
            "Give an emotional friendship speech to a spoon/object."
        ]
    },
    Teen: {
        truth: [
            "Ever tried to impress someone and totally cringed?",
            "Who in school/college do you secretly find cute?",
            "Have you ever typed a message to your crush and deleted it?",
            "What little white lie about friendship have you kept?",
            "When was the last time you bunked class with a lame excuse?",
            "Do you scroll group chats without replying?",
            "Any embarrassing reel drafts sitting in your phone?",
            "What weird face do you make when you see your crush?",
            "If you could mute one friend for life, who would it be?",
            "When do you become an overthinker?",
            "Ever had a teacher crush?",
            "What's the worst Insta bio you ever used?",
            "Have you ever made someone jealous on purpose?",
            "Your worst fashion fail?",
            "In fights do you cry first or roast first?",
            "Have you friend-zoned someone?",
            "Have you been friend-zoned?",
            "What silly thing did you fight with a friend over?",
            "Name a toxic habit you have.",
            "Do you sneak late-night snacks?",
            "Have you lied to impress someone?",
            "What matters more: love or studies?",
            "Who was your first crush? (Hint ok)",
            "Ever made a cringe reel to go viral?",
            "What's your most filmy moment?",
            "Do you miss an ex-best friend?",
            "Have you ever stalked an ex or crush?",
            "Ever pretended to be angry to get attention?",
            "Are you commitment-phobic or romantic?",
            "Are you more lover or villain energy?",
            "Share a funny toxic trait.",
            "Who in this group annoys you most?",
            "Are you secretly jealous often?",
            "How far would you go for love?",
            "What's the lamest compliment you've gotten?",
            "When were you overly dramatic for no reason?",
            "Which profile of yours gets the most secretly stalked views?",
            "Ever hung up saying \"battery low\"?",
            "What's your guilty-pleasure song?",
            "Which actor/actress is your mini-crush?",
            "Love marriage or arranged — what do you think?",
            "One thing your friends don't know about you?",
            "Party animal or home baby — what are you?",
            "How many times do you say \"I'm not toxic, but…\"?",
            "Are you a lover or an attention seeker?"
        ],
        dare: [
            "Do a slow-mo \"Hay Garmi\" style dance like a Bollywood item step.",
            "Deliver a 10-second dramatic villain line.",
            "Strike a crush-like pose without naming who it is.",
            "Call a friend and declare: \"I'm the hero of my life\" — don't hang up.",
            "Try an 8-second twerk-style funny move (only what's comfortable).",
            "Do a dramatic filmy proposal to your best friend.",
            "Dedicate a silly love line by singing to someone (funny, safe).",
            "Do a K-pop fan-style dramatic dance move.",
            "Do an influencer-style thumb-twist dance for a reel.",
            "Recite a cringey romantic shayari with full emotion.",
            "Use your hand as a baby and sing a lullaby for 20 seconds.",
            "Use a friend's shoe as a mic and sing one line.",
            "Show a random safe photo from your gallery.",
            "Give a 1-minute over-the-top motivational speech as an influencer.",
            "Act a breakup scene with full drama.",
            "Give a miss-call to a random number (consent if requested).",
            "Say a meme line with maximum energy.",
            "Put your hair in a hilarious style for 1 minute.",
            "Apologize seriously to a random object for 20 seconds.",
            "Draw makeup on your face without a mirror (with a washable pen).",
            "Dance using only eye movements for 15 seconds.",
            "Lead everyone in a \"friendship anthem\" chant.",
            "Try a moonwalk — even if it's wobbly.",
            "Say your best \"rizz\" pickup line.",
            "Tell a friend \"You're a legend\" ten times dramatically.",
            "Do an impression of a celebrity (respectful).",
            "Announce your future baby's name like it's news.",
            "Hug an object and call it \"my baby\" with full emotion.",
            "Pretend to be a classical singer for 30 seconds.",
            "Sing a breakup song but keep a straight face.",
            "Act like an animal and stay in character for 30 seconds.",
            "Make a 30-second fake motivational reel.",
            "Sing a song only using \"meow\" sounds.",
            "Sing a song only using \"woof/bark\" sounds.",
            "Do a hands-only dance for 15 seconds.",
            "Text a friend: \"If you don't pick up, I will cry\" (funny).",
            "Laugh non-stop for 10 seconds like laughter therapy.",
            "Write \"I'm Cute\" in your worst handwriting and show it.",
            "Treat a couch like your partner and have a short convo.",
            "Do a silly job-ad for your weirdest talent.",
            "Rap a 30-second verse about \"mummy ka danda.\"",
            "Sing while pretending to comb your hair seriously.",
            "Sing like you have a cold — exaggerate.",
            "Sing like something spicy went in your mouth — make faces.",
            "Do a 15-second backwards-sung line (try your best)."
        ]
    },
    Adult: {
        truth: [
            "What weird thing attracts you most in someone?",
            "Are you relationship material or a walking red flag?",
            "When are you fine doing the bare minimum in love?",
            "Do you react with jealousy or attitude?",
            "Have you used jealousy on someone before?",
            "Are you the rizz king/queen or a fail?",
            "Are you cute in love or possessive?",
            "Do you double-text?",
            "Which ex-type would you avoid forever?",
            "What's the dumbest reason you fell for someone?",
            "What was your most embarrassing date moment?",
            "Have you ever tested love with drama?",
            "Did you pull a glow-up after a breakup?",
            "Do you do silent treatment or over-talk?",
            "The silliest fight you had in a relationship — what was it?",
            "Loyalty 100% or entertainment allowed?",
            "Are you possessive with friends?",
            "Emotional or cold — which fits you?",
            "Ever fake-sorry after a kiss/gone weird?",
            "Do you push people away by overthinking?",
            "Have you said \"I'm busy\" as a lie?",
            "What makes you insecure?",
            "Flirt casually or mean it seriously?",
            "Fast reply or slow-burn texter?",
            "Do you take birthday wish drama personally?",
            "Do you play status games?",
            "Do you check your partner's phone?",
            "Do you let ego stop you from saying sorry?",
            "Do you fear making the first move?",
            "Split the bill or let someone pay — what do you prefer?",
            "Privacy-lover or clingy?",
            "Do small things hurt you easily?",
            "Ever kept someone as a backup option?",
            "Ever gone to someone just for attention?",
            "Ever blindly trusted someone who broke it?",
            "Ever flirted for revenge?",
            "Are you truly healed from your last heartbreak?",
            "Do you believe long-distance can work?",
            "Are you immature or way too mature in love?",
            "Do you fake \"I'm okay\" often?",
            "Do you secretly want someone to be crazy about you?",
            "Are you toxic or believe everyone else is?",
            "Do you give space or cling?",
            "Look or personality — what wins?",
            "Are you a real romantic or a social-media romantic?"
        ],
        dare: [
            "Do a 15-second Nora-Fatehi-style high-energy dance (hair flip allowed).",
            "Do a funny slow-mo \"Tu Cheez Badi Hai Mast Mast\" step.",
            "Read a romantic shayari to a pillow like it's your crush.",
            "Act a dramatic filmy breakup scene with full tears (funny allowed).",
            "Call a friend and say, \"I think I love you, bro/sis.\"",
            "Propose to a table: \"You are perfect.\"",
            "Do a 10-second twerk + bhangra mashup (comfort first).",
            "Do a 90s hero-style entry walk with attitude.",
            "Do a dramatic \"Tip Tip\" thumka (zero shame).",
            "Text a friend: \"Hurry up, get married, I'm bored\" (funny).",
            "Do a sultry-but-funny lipsync for 15 seconds.",
            "Sing \"Oh Humnava\" with two silly faces mid-line.",
            "Lipsync your favourite ex-song with full drama.",
            "Make an imaginary perfume ad for your friend.",
            "Recreate an embarrassing romantic reel (with permission).",
            "Sing a song using only the word \"baby.\"",
            "Sing a song in sultry slow-motion style.",
            "Toss your collar like an SRK pose and hold for 5 seconds.",
            "Do a wind-in-hair Hrithik-style pose (dramatic).",
            "Strike \"I'm too hot\" poses ten times.",
            "Give a friend a playful seductive look and say \"Got it?\"",
            "Do a ramp-walk like a Bollywood star.",
            "Sing a comedic rap about your \"adulting\" problems.",
            "Do a 30-second fake product jingle (ridiculous product).",
            "Sing a line like something spicy hit your tongue — dramatic coughs.",
            "Sing a line like you've caught a cold — overact.",
            "Treat your hand like your sweetheart and have a small convo.",
            "Say a romantic line to a friend without laughing.",
            "Do a 10-second \"drunk dance\" (silly, safe).",
            "Do the \"Badtameez Dil\" hook step for 10 seconds.",
            "Make a heart shape with your face expressions.",
            "Whisper to a friend: \"I'm special\" — keep a straight face.",
            "Draw a mustache or lipstick without a mirror (washable pen).",
            "Sing a sad ghazal line in full drama for 15 seconds.",
            "Do a wall-romance act where the wall is your lover.",
            "Turn any item's item number into a classical dance step for 20 seconds.",
            "Do a silly seductive chicken dance.",
            "Describe your ideal crush without naming them.",
            "Play hero in a 30-second scene where everyone adores you.",
            "Perform a fake slow-mo perfume commercial.",
            "Give a confident \"I'm too hot to handle\" speech.",
            "Type a fake breakup message but don't send it.",
            "Suggest rizz-nicknames for three friends.",
            "Walk in slow-mo and wink at everyone once.",
            "Sing \"I'm cute accept it\" as a dramatic anthem."
        ]
    }
};

// Hinglish Questions (Original)
export const QUESTIONS_HI = {
    Kids: {
        truth: [
            "Kya tum kabhi bina brush kiye school gaye ho?",
            "Tumhara sabse bada jhooth kya tha jo mummy pakad gayi?",
            "Kaun tumhara best friend hai aur kyun?",
            "Kaunsa cartoon tum secret mein aaj bhi dekhte ho?",
            "Kya tum kabhi kisi ko homework copy karne diya?",
            "Kya tumhara kabhi teacher pe crush hua?",
            "Kya tum school ki assembly mein so gaye ho?",
            "Kya tum class mein dance karte pakde gaye ho?",
            "Kaunsi ice-cream tum 100 baar daily kha sakte ho?",
            "Tumhara funniest nickname kya hai?",
            "Kya tum kabhi ghar mein khana phekke chup-chap chips khaye ho?",
            "Kya tumhe kabhi raat ko bhoot bhoot lagta hai?",
            "Kaun se superpower tum chahte ho?",
            "Sabse weird cheez jo tumne khaayi?",
            "Tumhara sabse embarrassing moment school mein?",
            "Kaunse subject se tum darta/darti ho?",
            "Agar tum teacher ban jao toh first punishment kya doge?",
            "Ek cheez jo tum bilkul pasand nahi karte?",
            "Agar tumhe ek pet mile toh kaunsa chahoge?",
            "Kya tum kisi ka birthday cake taste se pehle secretly lick kiya hai?"
        ],
        dare: [
            "Apna favourite cartoon character ki awaaz nikaalo.",
            "Ek Bollywood hero/heroine ki style mein 10 second acting karo.",
            "Ek funny dance karo jaise noodles hil rahe ho.",
            "Nani Teri Morni Ko Mor Le Gaye full jazbaat se gaao.",
            "Robot ban kar 20 second walk karo.",
            "Catwalk karo jaise fashion show ho raha hai.",
            "Chicken dance karo.",
            "Alphabet ulta bolne ki koshish karo (jitna ho sake).",
            "Table ko propose karo full emotion ke saath.",
            "Ek teacher ban kar sab ko homework sunao.",
            "Apna favourite cartoon pose karo.",
            "Joker ki tarah hasi hanso.",
            "Slow motion mein running karo.",
            "Kisi ke pair ko mic bannakar gaana gaao.",
            "Ek animal sound mix beatbox banao.",
            "Ek tabla player ban kar table bajao.",
            "Apna hair funny style mein set karo.",
            "10 second mein jitne funny faces bana sakte ho banao.",
            "Ek movie villain ki dialogue bolo.",
            "Ek object ko dosti ka emotional speech do."
        ]
    },
    Teen: {
        truth: [
            "Kya tum kabhi kisi ko impress karne ke chakkar mein cringe ho gaye?",
            "School/college mein kaun tumhe sabse cute lagta hai?",
            "Kya tum kabhi crush ko message likh kar delete kar dete ho?",
            "Kaun sa dosti ka jhooth tumne aaj tak chupaya?",
            "Last time kab bakwaas reason bolkar class bunk kiya?",
            "Kya tum group chat stalk karte ho bina reply kiye?",
            "Tumhara sabse embarrassing reel draft mein pada hua?",
            "Apna crush ko dekh ke kaun sa weird expression aa jata?",
            "Agar ek friend ko life se mute kar sakte ho toh kaun?",
            "Kahan tum overthinking champions ban jaate ho?",
            "Kya tumko kabhi teacher par thoda crush hua tha?",
            "Most weird Insta bio jo tumne kabhi lagaya?",
            "Kissi ko jealous feel karwane ka karnama kiya?",
            "Worst fashion mistake tumhari?",
            "Tum jhagda hota toh pehle ro lete ya roast karte?",
            "Kya tumne kisi ko friendzone kiya?",
            "Kya kisi ne tumhe friendzone kiya?",
            "Sabse useless thing jiske liye tumne fight kiya?",
            "Apna toxic habit bolo.",
            "Kya tum late night secretly snacks khaate ho?",
            "Kisi ko impress karne ke liye jhooth bola tha?",
            "Pyaar ya padhai – konsa priority?",
            "Tumhara pehla crush ka naam?",
            "Kya tum G.O.A.T banne ke chakkar mein cringe reel banayi?",
            "Tumhari life ka sabse filmy moment?",
            "Kisi ex-best friend ki yaad aati hai?",
            "Ex ya crush stalk kiya kabhi?",
            "Kisi ka status reply ke liye sirf scene banaya?",
            "Breaking news – tum commitment phobic ho ya romantic?",
            "Tum stereotypical lover ho ya villain energy?",
            "Tumhari toxic trait batao (funny ho to better).",
            "Group mein sabse zyada kaun irritate karta?",
            "Tum kabhi jealous hote ho secretly?",
            "Tum pyar ke liye kitni had tak jaa sakte?",
            "Sabse lame compliment jo mila?",
            "Recent overdramatic moment jo unnecessary tha?",
            "Tumhari sabse zyada stalk ki gayi profile kaunsi?",
            "Kisi se call jald hi kat diya battery low jhooth bolkar?",
            "Tumhari guilty pleasure song?",
            "Kaunsa actor/actress par tumhara mini crush?",
            "Love marriage ya arranged – kya sochte ho?",
            "Ek cheez jo tumhare friends ko bilkul nahi pata?",
            "Tum party animal ho ya home baby?",
            "Kitne percent main toxic nahi hoon but real hai?",
            "Dilon ka dil – tum lover ho ya attention seeker?"
        ],
        dare: [
            "Nora Fatehi ke style mein Garmi step 10 sec dance karo.",
            "Ek Bollywood villain ban kar dramatic dialogue bolo.",
            "Apne crush ki tara pose karo aur uska naam mat batao.",
            "Ek friend ko call karo aur bolo main life mein hero hoon phir cut mat karna.",
            "Twerking style mein funny dance 8 seconds.",
            "Apne best friend ke liye dramatic filmy proposal karo.",
            "Kisi ko tum mere hero ho gaana gaa kar dedicate karo.",
            "K-pop fan ban kar dramatic dance karo.",
            "Instagram wala thumka reel style mein.",
            "Ek shayari sunao full cringe romantic.",
            "Apne haath ko baby bolkar 20 sec lullaby gaao.",
            "Ek friend ke pair ko mic banaakar gaana gaao.",
            "Apna phone gallery ka random pic sabko dikhao (safe wala choose).",
            "Ek minute ke liye influencer ban kar motivational speech.",
            "Ek sad breakup scene act karo bina reason ke.",
            "Ek random number ko miss call maaro (phir block karlo).",
            "Ek meme dialogue full energy mein bolo.",
            "Apna hairstyle fully funny bana lo 1 minute ke liye.",
            "Ek random cheese ko baat-baat mein sorry bolo.",
            "Mirror ke bina make-up draw karo chehre par (safe pen).",
            "Ek dance step sirf aankhon se karo.",
            "Ek dosti anthem bankar group ko cheer up karo.",
            "Sab ke saamne moonwalk karne ki koshish karo.",
            "Apne naam ke sath ek rizz line bolo.",
            "Apne dost ko bhai tu legend ho 10 baar bolo.",
            "Kisi celebrity ka impression.",
            "Apna future baby name announcement karo.",
            "Kisi ek cheez ko mera bachcha bolkar hug karo.",
            "Ek classical singer ban kar gaao.",
            "Chicken walk + attitude catwalk mix.",
            "Ek breakup song gaao aur hanso nahi.",
            "Apna jaanwar version acting karo.",
            "Ek motivational reel banaane ka drama.",
            "Ek gaana gaao sirf meow meow words mein.",
            "Ek gaana gaao sirf bhau bhau words mein.",
            "Hands-only dance 15 sec.",
            "Ek friend ko bhai tu phone na uthaya toh main toot jaunga message bhejo.",
            "10 sec nonstop laughter therapy.",
            "Apni sabse gandi handwriting mein I'm Cute likho.",
            "Couch ko girlfriend/boyfriend treat karke baat karo.",
            "Rozgaar ad jaisa apna talent advertise karo.",
            "Ek rap banao mummy ka danda topic par.",
            "Apne baal pe riyaaz krte hue singing karo.",
            "Ek gaana gaao jaise cold lag rahi ho.",
            "Ek gaana gaao jaise mirchi lag gayi ho."
        ]
    },
    Adult: {
        truth: [
            "Sabse weird attraction kis wajah se hota hai?",
            "Tum relationship material ho ya red flag khud?",
            "Tumhara bare minimum se pyaar kab ON hota hai?",
            "Tum jealous hona accept karoge ya attitude doge?",
            "Tumne last time jealousy trap use kiya?",
            "Tum rizz king/queen ho ya failure?",
            "Tum pyaar mein cute ho ya possessive?",
            "Kya tum double texting karte ho?",
            "Kaunse ex-type se door rehna chahoge forever?",
            "Sabse lamest reason jis wajah se pyar hua?",
            "Tumhari date pe sabse embarrassing moment?",
            "Tum drama kar ke pyaar test karte ho?",
            "Tum breakup ke baad glow-up kiya?",
            "Tum silent treatment dete ho ya overtalk?",
            "Relationship ka sabse stupid fight kis baat pe?",
            "Tum loyalty 100% ho ya entertainment bhi chalta hai?",
            "Tum dosti mein possessive ho?",
            "Tum emotional ho ya cold?",
            "Last time kiss ko fake sorry bola?",
            "Tum overthinking se logo ko bhagaa dete ho?",
            "Tumne kisi ko aaj busy hoon jhooth bola?",
            "Tum insecure ho? Kis cheez se?",
            "Tum flirting casual rakhte ho ya serious?",
            "Tum fast reply wale ho ya slow poison?",
            "Tum birthday wish ka dard rakhe hue ho?",
            "Tum status games khelte ho?",
            "Tum phone check karte ho relationship mein?",
            "Tum ego ke chakkar mein sorry nahi bolte?",
            "Tum first move karne se darte ho?",
            "Tum date par bill share karna pasand karte ho?",
            "Tum privacy lover ho ya attachment lover?",
            "Tum chhoti baat pe hurt feel karte ho?",
            "Tum kabhi kisi ko extra option bana kar rakha?",
            "Tum kabhi kisi ke paas sirf attention ke liye gaye?",
            "Tum kabhi kisi pe blind trust kiya?",
            "Tum kabhi kisi ke saath revenge flirt kiya?",
            "Tum heartbreak se recover huye ho ya acting chal rahi hai?",
            "Tum long distance believe karte ho?",
            "Tum pyaar mein immature ho ya overmature?",
            "Tum I'm fine bol ke drama banate ho?",
            "Tum chaate ho koi tum par crazy ho jaye?",
            "Tum toxic ho ya main perfect hoon but log hi galat hai?",
            "Tum relationship mein space doge?",
            "Tum sirf looks dekhte ho ya personality matter?",
            "Tum real romantic ho ya social media romantic?"
        ],
        dare: [
            "Nora Fatehi O Saki Saki style 15 sec dance.",
            "Tu cheez badi hai mast mast sexy slow-mo dance – funny way.",
            "Ek romantic shayari kisi pillow ko bolkar.",
            "Ek filmy breakup scene act karo bina wajah.",
            "Ek friend ko call karke bolo: I think I love you bro/sis.",
            "Kisi table ko propose karo: Tum perfect ho.",
            "Twerk + bhangra mix 10 sec.",
            "90s hero ban kar entry banao.",
            "Tip Tip Barsa Pani dramatic thumka – but zero shame.",
            "Kisi dost ko jaldi shaadi karlo main bore hoon text karo.",
            "Eyes-only seduction dance.",
            "Oh Humnava Mere gaao aur beech mein 2 funny faces dikhana.",
            "Apne favourite ex-song pe lipsync full attitude.",
            "Apne partner/friend ka imaginary perfume ad banao.",
            "Ek cringe romantic reel recreate karo.",
            "Ek gaana sirf baby word se gaao.",
            "Koi bhi gaana sensual slow motion style mein gaao.",
            "Apna shirt/collar ko Shahrukh style hawa mein udao.",
            "Apna hairstyle Hrithik Krrish style hawa mein udao.",
            "Mummy kasam I'm too hot pose 10 baar.",
            "Ek friend ko sexy nazar dekh kar bolo samajh gaye?",
            "Ramp walk as if you are Katrina entry.",
            "Ek gaana gaao jaise shayari lover heartbreak king.",
            "Ek rap banao meri zindagi ka dard – par comedy version.",
            "Ek gaana gaao jaise mirchi lag rahi ho.",
            "Ek gaana gaao jaise thand lag rahi ho.",
            "Apne haath ko girlfriend/boyfriend treat karo.",
            "Ek friend ko romantic line bolo bina hansi ke.",
            "Sharabi dance 10 sec bina music.",
            "Badtameez Dil hook step 10 sec.",
            "Ek heart emoji face se banao.",
            "Ek friend ke kaan mein whisper karo: Main khaas hoon.",
            "Mirror ke bina lipstick/mustache draw karo.",
            "Ek sad ghazal singer ban kar 15 sec gao.",
            "Bollywood style wall romance acting but wall ke saath.",
            "Kisi bhi item number ko classical Bharatanatyam style karo.",
            "Chicken dance lekin seductive try karo.",
            "Apni crush type ko describe karo bina naam bataye.",
            "Ek scene karo jisme tum hero ho aur sab tum par fida hain.",
            "Ek fake perfume ad – over drama + slow-mo.",
            "Ek I'm too hot to handle speech full confidence.",
            "Ek fake breakup message type karo but send mat karna.",
            "Apne doston ka rizz name suggest karo.",
            "Group ke beech mein slow-mo wink walk.",
            "Main cute hoon accept kar lo gana full feel mein gaao."
        ]
    }
};

// Default export for backward compatibility
export const QUESTIONS = QUESTIONS_HI;
