export const QUESTIONS = {
    Kids: {
        truth: [
            "Kya tum kabhi bina brush kiye school gaye ho?",
            "Tumhara sabse bada jhooth kya tha jo mummy pakad gayi?",
            "Kaun tumhara best friend hai aur kyun?",
            "Kaunsa cartoon tum secret mein aaj bhi dekhte ho?",
            "Kya tum kabhi kisi ko homework copy karne diya?",
            "Kya tumhara kabhi teacher pe crush hua?",
            "Kya tum school ki assembly mein so gaye ho?",
            "Kya tum class mein dance karte pakde gaye ho?",
            "Kaunsi ice-cream tum 100 baar daily kha sakte ho?",
            "Tumhara funniest nickname kya hai?",
            "Kya tum kabhi ghar mein khana phekke chup-chap chips khaye ho?",
            "Kya tumhe kabhi raat ko bhoot bhoot lagta hai?",
            "Kaun se superpower tum chahte ho?",
            "Sabse weird cheez jo tumne khaayi?",
            "Tumhara sabse embarrassing moment school mein?",
            "Kaunse subject se tum darta/darti ho?",
            "Agar tum teacher ban jao toh first punishment kya doge?",
            "Ek cheez jo tum bilkul pasand nahi karte?",
            "Agar tumhe ek pet mile toh kaunsa chahoge?",
            "Kya tum kisi ka birthday cake taste se pehle secretly lick kiya hai?"
        ],
        dare: [
            "Apna favourite cartoon character ki awaaz nikaalo.",
            "Ek Bollywood hero/heroine ki style mein 10 second acting karo.",
            "Ek funny dance karo jaise noodles hil rahe ho.",
            "Nani Teri Morni Ko Mor Le Gaye full jazbaat se gaao.",
            "Robot ban kar 20 second walk karo.",
            "Catwalk karo jaise fashion show ho raha hai.",
            "Chicken dance karo.",
            "Alphabet ulta bolne ki koshish karo (jitna ho sake).",
            "Table ko propose karo full emotion ke saath.",
            "Ek teacher ban kar sab ko homework sunao.",
            "Apna favourite cartoon pose karo.",
            "Joker ki tarah hasi hanso.",
            "Slow motion mein running karo.",
            "Kisi ke pair ko mic bannakar gaana gaao.",
            "Ek animal sound mix beatbox banao.",
            "Ek tabla player ban kar table bajao.",
            "Apna hair funny style mein set karo.",
            "10 second mein jitne funny faces bana sakte ho banao.",
            "Ek movie villain ki dialogue bolo.",
            "Ek object ko dosti ka emotional speech do."
        ]
    },
    Teen: {
        truth: [
            "Kya tum kabhi kisi ko impress karne ke chakkar mein cringe ho gaye?",
            "School/college mein kaun tumhe sabse cute lagta hai?",
            "Kya tum kabhi crush ko message likh kar delete kar dete ho?",
            "Kaun sa dosti ka jhooth tumne aaj tak chupaya?",
            "Last time kab bakwaas reason bolkar class bunk kiya?",
            "Kya tum group chat stalk karte ho bina reply kiye?",
            "Tumhara sabse embarrassing reel draft mein pada hua?",
            "Apna crush ko dekh ke kaun sa weird expression aa jata?",
            "Agar ek friend ko life se mute kar sakte ho toh kaun?",
            "Kahan tum overthinking champions ban jaate ho?",
            "Kya tumko kabhi teacher par thoda crush hua tha?",
            "Most weird Insta bio jo tumne kabhi lagaya?",
            "Kissi ko jealous feel karwane ka karnama kiya?",
            "Worst fashion mistake tumhari?",
            "Tum jhagda hota toh pehle ro lete ya roast karte?",
            "Kya tumne kisi ko friendzone kiya?",
            "Kya kisi ne tumhe friendzone kiya?",
            "Sabse useless thing jiske liye tumne fight kiya?",
            "Apna toxic habit bolo.",
            "Kya tum late night secretly snacks khaate ho?",
            "Kisi ko impress karne ke liye jhooth bola tha?",
            "Pyaar ya padhai – konsa priority?",
            "Tumhara pehla crush ka naam?",
            "Kya tum G.O.A.T banne ke chakkar mein cringe reel banayi?",
            "Tumhari life ka sabse filmy moment?",
            "Kisi ex-best friend ki yaad aati hai?",
            "Ex ya crush stalk kiya kabhi?",
            "Kisi ka status reply ke liye sirf scene banaya?",
            "Breaking news – tum commitment phobic ho ya romantic?",
            "Tum stereotypical lover ho ya villain energy?",
            "Tumhari toxic trait batao (funny ho to better).",
            "Group mein sabse zyada kaun irritate karta?",
            "Tum kabhi jealous hote ho secretly?",
            "Tum pyar ke liye kitni had tak jaa sakte?",
            "Sabse lame compliment jo mila?",
            "Recent overdramatic moment jo unnecessary tha?",
            "Tumhari sabse zyada stalk ki gayi profile kaunsi?",
            "Kisi se call jald hi kat diya battery low jhooth bolkar?",
            "Tumhari guilty pleasure song?",
            "Kaunsa actor/actress par tumhara mini crush?",
            "Love marriage ya arranged – kya sochte ho?",
            "Ek cheez jo tumhare friends ko bilkul nahi pata?",
            "Tum party animal ho ya home baby?",
            "Kitne percent main toxic nahi hoon but real hai?",
            "Dilon ka dil – tum lover ho ya attention seeker?"
        ],
        dare: [
            "Nora Fatehi ke style mein Garmi step 10 sec dance karo.",
            "Ek Bollywood villain ban kar dramatic dialogue bolo.",
            "Apne crush ki tara pose karo aur uska naam mat batao.",
            "Ek friend ko call karo aur bolo main life mein hero hoon phir cut mat karna.",
            "Twerking style mein funny dance 8 seconds.",
            "Apne best friend ke liye dramatic filmy proposal karo.",
            "Kisi ko tum mere hero ho gaana gaa kar dedicate karo.",
            "K-pop fan ban kar dramatic dance karo.",
            "Instagram wala thumka reel style mein.",
            "Ek shayari sunao full cringe romantic.",
            "Apne haath ko baby bolkar 20 sec lullaby gaao.",
            "Ek friend ke pair ko mic banaakar gaana gaao.",
            "Apna phone gallery ka random pic sabko dikhao (safe wala choose).",
            "Ek minute ke liye influencer ban kar motivational speech.",
            "Ek sad breakup scene act karo bina reason ke.",
            "Ek random number ko miss call maaro (phir block karlo).",
            "Ek meme dialogue full energy mein bolo.",
            "Apna hairstyle fully funny bana lo 1 minute ke liye.",
            "Ek random cheese ko baat-baat mein sorry bolo.",
            "Mirror ke bina make-up draw karo chehre par (safe pen).",
            "Ek dance step sirf aankhon se karo.",
            "Ek dosti anthem bankar group ko cheer up karo.",
            "Sab ke saamne moonwalk karne ki koshish karo.",
            "Apne naam ke sath ek rizz line bolo.",
            "Apne dost ko bhai tu legend ho 10 baar bolo.",
            "Kisi celebrity ka impression.",
            "Apna future baby name announcement karo.",
            "Kisi ek cheez ko mera bachcha bolkar hug karo.",
            "Ek classical singer ban kar gaao.",
            "Chicken walk + attitude catwalk mix.",
            "Ek breakup song gaao aur hanso nahi.",
            "Apna jaanwar version acting karo.",
            "Ek motivational reel banaane ka drama.",
            "Ek gaana gaao sirf meow meow words mein.",
            "Ek gaana gaao sirf bhau bhau words mein.",
            "Hands-only dance 15 sec.",
            "Ek friend ko bhai tu phone na uthaya toh main toot jaunga message bhejo.",
            "10 sec nonstop laughter therapy.",
            "Apni sabse gandi handwriting mein I'm Cute likho.",
            "Couch ko girlfriend/boyfriend treat karke baat karo.",
            "Rozgaar ad jaisa apna talent advertise karo.",
            "Ek rap banao mummy ka danda topic par.",
            "Apne baal pe riyaaz krte hue singing karo.",
            "Ek gaana gaao jaise cold lag rahi ho.",
            "Ek gaana gaao jaise mirchi lag gayi ho."
        ]
    },
    Adult: {
        truth: [
            "Sabse weird attraction kis wajah se hota hai?",
            "Tum relationship material ho ya red flag khud?",
            "Tumhara bare minimum se pyaar kab ON hota hai?",
            "Tum jealous hona accept karoge ya attitude doge?",
            "Tumne last time jealousy trap use kiya?",
            "Tum rizz king/queen ho ya failure?",
            "Tum pyaar mein cute ho ya possessive?",
            "Kya tum double texting karte ho?",
            "Kaunse ex-type se door rehna chahoge forever?",
            "Sabse lamest reason jis wajah se pyar hua?",
            "Tumhari date pe sabse embarrassing moment?",
            "Tum drama kar ke pyaar test karte ho?",
            "Tum breakup ke baad glow-up kiya?",
            "Tum silent treatment dete ho ya overtalk?",
            "Relationship ka sabse stupid fight kis baat pe?",
            "Tum loyalty 100% ho ya entertainment bhi chalta hai?",
            "Tum dosti mein possessive ho?",
            "Tum emotional ho ya cold?",
            "Last time kiss ko fake sorry bola?",
            "Tum overthinking se logo ko bhagaa dete ho?",
            "Tumne kisi ko aaj busy hoon jhooth bola?",
            "Tum insecure ho? Kis cheez se?",
            "Tum flirting casual rakhte ho ya serious?",
            "Tum fast reply wale ho ya slow poison?",
            "Tum birthday wish ka dard rakhe hue ho?",
            "Tum status games khelte ho?",
            "Tum phone check karte ho relationship mein?",
            "Tum ego ke chakkar mein sorry nahi bolte?",
            "Tum first move karne se darte ho?",
            "Tum date par bill share karna pasand karte ho?",
            "Tum privacy lover ho ya attachment lover?",
            "Tum chhoti baat pe hurt feel karte ho?",
            "Tum kabhi kisi ko extra option bana kar rakha?",
            "Tum kabhi kisi ke paas sirf attention ke liye gaye?",
            "Tum kabhi kisi pe blind trust kiya?",
            "Tum kabhi kisi ke saath revenge flirt kiya?",
            "Tum heartbreak se recover huye ho ya acting chal rahi hai?",
            "Tum long distance believe karte ho?",
            "Tum pyaar mein immature ho ya overmature?",
            "Tum I'm fine bol ke drama banate ho?",
            "Tum chaate ho koi tum par crazy ho jaye?",
            "Tum toxic ho ya main perfect hoon but log hi galat hai?",
            "Tum relationship mein space doge?",
            "Tum sirf looks dekhte ho ya personality matter?",
            "Tum real romantic ho ya social media romantic?"
        ],
        dare: [
            "Nora Fatehi O Saki Saki style 15 sec dance.",
            "Tu cheez badi hai mast mast sexy slow-mo dance – funny way.",
            "Ek romantic shayari kisi pillow ko bolkar.",
            "Ek filmy breakup scene act karo bina wajah.",
            "Ek friend ko call karke bolo: I think I love you bro/sis.",
            "Kisi table ko propose karo: Tum perfect ho.",
            "Twerk + bhangra mix 10 sec.",
            "90s hero ban kar entry banao.",
            "Tip Tip Barsa Pani dramatic thumka – but zero shame.",
            "Kisi dost ko jaldi shaadi karlo main bore hoon text karo.",
            "Eyes-only seduction dance.",
            "Oh Humnava Mere gaao aur beech mein 2 funny faces dikhana.",
            "Apne favourite ex-song pe lipsync full attitude.",
            "Apne partner/friend ka imaginary perfume ad banao.",
            "Ek cringe romantic reel recreate karo.",
            "Ek gaana sirf baby word se gaao.",
            "Koi bhi gaana sensual slow motion style mein gaao.",
            "Apna shirt/collar ko Shahrukh style hawa mein udao.",
            "Apna hairstyle Hrithik Krrish style hawa mein udao.",
            "Mummy kasam I'm too hot pose 10 baar.",
            "Ek friend ko sexy nazar dekh kar bolo samajh gaye?",
            "Ramp walk as if you are Katrina entry.",
            "Ek gaana gaao jaise shayari lover heartbreak king.",
            "Ek rap banao meri zindagi ka dard – par comedy version.",
            "Ek gaana gaao jaise mirchi lag rahi ho.",
            "Ek gaana gaao jaise thand lag rahi ho.",
            "Apne haath ko girlfriend/boyfriend treat karo.",
            "Ek friend ko romantic line bolo bina hansi ke.",
            "Sharabi dance 10 sec bina music.",
            "Badtameez Dil hook step 10 sec.",
            "Ek heart emoji face se banao.",
            "Ek friend ke kaan mein whisper karo: Main khaas hoon.",
            "Mirror ke bina lipstick/mustache draw karo.",
            "Ek sad ghazal singer ban kar 15 sec gao.",
            "Bollywood style wall romance acting but wall ke saath.",
            "Kisi bhi item number ko classical Bharatanatyam style karo.",
            "Chicken dance lekin seductive try karo.",
            "Apni crush type ko describe karo bina naam bataye.",
            "Ek scene karo jisme tum hero ho aur sab tum par fida hain.",
            "Ek fake perfume ad – over drama + slow-mo.",
            "Ek I'm too hot to handle speech full confidence.",
            "Ek fake breakup message type karo but send mat karna.",
            "Apne doston ka rizz name suggest karo.",
            "Group ke beech mein slow-mo wink walk.",
            "Main cute hoon accept kar lo gana full feel mein gaao."
        ]
    }
};
